// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: newsfeed_publishing.proto

package newsfeed_publishing

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishPostResponse_PublishPostResponseStatus int32

const (
	PublishPostResponse_OK     PublishPostResponse_PublishPostResponseStatus = 0
	PublishPostResponse_FAILED PublishPostResponse_PublishPostResponseStatus = 1
)

// Enum value maps for PublishPostResponse_PublishPostResponseStatus.
var (
	PublishPostResponse_PublishPostResponseStatus_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	PublishPostResponse_PublishPostResponseStatus_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x PublishPostResponse_PublishPostResponseStatus) Enum() *PublishPostResponse_PublishPostResponseStatus {
	p := new(PublishPostResponse_PublishPostResponseStatus)
	*p = x
	return p
}

func (x PublishPostResponse_PublishPostResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishPostResponse_PublishPostResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_newsfeed_publishing_proto_enumTypes[0].Descriptor()
}

func (PublishPostResponse_PublishPostResponseStatus) Type() protoreflect.EnumType {
	return &file_newsfeed_publishing_proto_enumTypes[0]
}

func (x PublishPostResponse_PublishPostResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishPostResponse_PublishPostResponseStatus.Descriptor instead.
func (PublishPostResponse_PublishPostResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_newsfeed_publishing_proto_rawDescGZIP(), []int{1, 0}
}

type PublishPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64                `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId    int64                `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *PublishPostRequest) Reset() {
	*x = PublishPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newsfeed_publishing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPostRequest) ProtoMessage() {}

func (x *PublishPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newsfeed_publishing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPostRequest.ProtoReflect.Descriptor instead.
func (*PublishPostRequest) Descriptor() ([]byte, []int) {
	return file_newsfeed_publishing_proto_rawDescGZIP(), []int{0}
}

func (x *PublishPostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishPostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PublishPostRequest) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PublishPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status PublishPostResponse_PublishPostResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=newsfeed_publishing.PublishPostResponse_PublishPostResponseStatus" json:"status,omitempty"`
}

func (x *PublishPostResponse) Reset() {
	*x = PublishPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newsfeed_publishing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPostResponse) ProtoMessage() {}

func (x *PublishPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newsfeed_publishing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPostResponse.ProtoReflect.Descriptor instead.
func (*PublishPostResponse) Descriptor() ([]byte, []int) {
	return file_newsfeed_publishing_proto_rawDescGZIP(), []int{1}
}

func (x *PublishPostResponse) GetStatus() PublishPostResponse_PublishPostResponseStatus {
	if x != nil {
		return x.Status
	}
	return PublishPostResponse_OK
}

var File_newsfeed_publishing_proto protoreflect.FileDescriptor

var file_newsfeed_publishing_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6e, 0x65, 0x77,
	0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x81, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x42, 0x2e,
	0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x69, 0x6e, 0x67, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f, 0x0a, 0x19, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x32, 0x78, 0x0a, 0x12, 0x4e, 0x65,
	0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67,
	0x12, 0x62, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x12,
	0x27, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x66,
	0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x78, 0x75, 0x61, 0x6e, 0x71, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62,
	0x2f, 0x6e, 0x65, 0x77, 0x73, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_newsfeed_publishing_proto_rawDescOnce sync.Once
	file_newsfeed_publishing_proto_rawDescData = file_newsfeed_publishing_proto_rawDesc
)

func file_newsfeed_publishing_proto_rawDescGZIP() []byte {
	file_newsfeed_publishing_proto_rawDescOnce.Do(func() {
		file_newsfeed_publishing_proto_rawDescData = protoimpl.X.CompressGZIP(file_newsfeed_publishing_proto_rawDescData)
	})
	return file_newsfeed_publishing_proto_rawDescData
}

var file_newsfeed_publishing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_newsfeed_publishing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_newsfeed_publishing_proto_goTypes = []interface{}{
	(PublishPostResponse_PublishPostResponseStatus)(0), // 0: newsfeed_publishing.PublishPostResponse.PublishPostResponseStatus
	(*PublishPostRequest)(nil),                         // 1: newsfeed_publishing.PublishPostRequest
	(*PublishPostResponse)(nil),                        // 2: newsfeed_publishing.PublishPostResponse
	(*timestamp.Timestamp)(nil),                        // 3: google.protobuf.Timestamp
}
var file_newsfeed_publishing_proto_depIdxs = []int32{
	3, // 0: newsfeed_publishing.PublishPostRequest.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: newsfeed_publishing.PublishPostResponse.status:type_name -> newsfeed_publishing.PublishPostResponse.PublishPostResponseStatus
	1, // 2: newsfeed_publishing.NewsfeedPublishing.PublishPost:input_type -> newsfeed_publishing.PublishPostRequest
	2, // 3: newsfeed_publishing.NewsfeedPublishing.PublishPost:output_type -> newsfeed_publishing.PublishPostResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_newsfeed_publishing_proto_init() }
func file_newsfeed_publishing_proto_init() {
	if File_newsfeed_publishing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_newsfeed_publishing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_newsfeed_publishing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_newsfeed_publishing_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_newsfeed_publishing_proto_goTypes,
		DependencyIndexes: file_newsfeed_publishing_proto_depIdxs,
		EnumInfos:         file_newsfeed_publishing_proto_enumTypes,
		MessageInfos:      file_newsfeed_publishing_proto_msgTypes,
	}.Build()
	File_newsfeed_publishing_proto = out.File
	file_newsfeed_publishing_proto_rawDesc = nil
	file_newsfeed_publishing_proto_goTypes = nil
	file_newsfeed_publishing_proto_depIdxs = nil
}
